### ISSUE TITLE
Crea tu cuenta 

### ISSUE THREAD

**Issue by FranBudde** [micaelaberto/MERCADO_LIEBRE_MB#5]
la animacion de limpiar esta rara, despus en donde esta para subir un archivo el error esta en que acepta subir cualquier archivo y tendria que dejar subir nomas archivos jpg y png, tambien la Ñ en contraseña esta muy chica pero eso debe ser la tipografia, despues esta todo perfecto

**Comment by micaelaberto** [comment]
Modificado
